import type { DynamicTableColumn } from "../dynamic-table/types";

export const vehiclesColumns: DynamicTableColumn[] = [
  {
    header: "ID",
    accessorKey: "id",
    type: "text",
    sortable: false,
    modifiable: false,
  },
  {
    header: "Imágenes",
    accessorKey: "images",
    type: "array",
    showArrayItems: false,
    sortable: false,
    modifiable: false,
  },
  {
    header: "Título",
    accessorKey: "title",
    type: "text",
    sortable: true,
  },
  {
    header: "Categoría",
    accessorKey: "category.name",
    type: "text",
    sortable: false,
    modifiable: false,
  },
  {
    header: "Estado",
    accessorKey: "status",
    type: "badge",
    sortable: true,
  },
  {
    header: "Destacado",
    accessorKey: "is_featured",
    type: "boolean",
    sortable: true,
  },
  {
    header: "Precio",
    accessorKey: "price",
    type: "number",
    sortable: true,
  },
  {
    header: "Kilometraje",
    accessorKey: "mileage",
    type: "number",
    sortable: true,
  },
  {
    header: "Visitas",
    accessorKey: "views",
    type: "number",
    sortable: true,
  },
  {
    header: "Transmisión",
    accessorKey: "transmission_type",
    type: "badge",
    sortable: false,
  },
  {
    header: "Potencia (CV)",
    accessorKey: "power",
    type: "number",
    sortable: false,
  },
  {
    header: "Cilindrada (cc)",
    accessorKey: "displacement",
    type: "number",
    sortable: false,
  },
  {
    header: "Condición",
    accessorKey: "condition",
    type: "badge",
    sortable: false,
  },
  {
    header: "Tracción",
    accessorKey: "traction.name",
    type: "text",
    sortable: false,
    modifiable: false,
  },
  {
    header: "Autonomía (km)",
    accessorKey: "autonomy",
    type: "number",
    sortable: false,
  },
  {
    header: "Capacidad batería",
    accessorKey: "battery_capacity",
    type: "number",
    sortable: false,
  },
  {
    header: "Tiempo de carga",
    accessorKey: "time_to_charge",
    type: "number",
    sortable: false,
  },
  {
    header: "Latitud",
    accessorKey: "lat",
    type: "text",
    sortable: false,
  },
  {
    header: "Longitud",
    accessorKey: "lng",
    type: "text",
    sortable: false,
  },
  {
    header: "Tipo de publicador",
    accessorKey: "publisher_type",
    type: "badge",
    sortable: false,
  },
  {
    header: "Publicador",
    accessorKey: "publisher.name",
    type: "text",
    sortable: false,
    modifiable: false,
  },
  {
    header: "Teléfono",
    accessorKey: "phone",
    type: "text",
    sortable: false,
  },
  {
    header: "Correo electrónico",
    accessorKey: "email",
    type: "text",
    sortable: false,
  },
  {
    header: "Matrícula",
    accessorKey: "license_plate",
    type: "text",
  },
  {
    header: "Versión",
    accessorKey: "version_id",
    type: "number",
    sortable: false,
  },
  {
    header: "Tipo de vehículo",
    accessorKey: "vehicle_type.name",
    type: "text",
    sortable: false,
    modifiable: false,
  },
  {
    header: "Fecha de creación",
    accessorKey: "created_at",
    type: "date",
    sortable: true,
    modifiable: false,
  },
  {
    header: "Fecha de actualización",
    accessorKey: "updated_at",
    type: "date",
    sortable: true,
    modifiable: false,
  },
  {
    header: "Fecha de expiración",
    accessorKey: "expires_at",
    type: "date",
    sortable: true,
  },
];
