/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SignInIndexRouteImport } from './routes/signIn/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRecoverPasswordRouteImport } from './routes/auth/recover-password'
import { Route as AuthenticatedWarrantyTypesRouteImport } from './routes/_authenticated/warranty-types'
import { Route as AuthenticatedVersionesRouteImport } from './routes/_authenticated/versiones'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedVehicleTypesRouteImport } from './routes/_authenticated/vehicle-types'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTractionsRouteImport } from './routes/_authenticated/tractions'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedTicketCategoriesRouteImport } from './routes/_authenticated/ticket-categories'
import { Route as AuthenticatedTasacionesRouteImport } from './routes/_authenticated/tasaciones'
import { Route as AuthenticatedSubscriptionPlansRouteImport } from './routes/_authenticated/subscription-plans'
import { Route as AuthenticatedRoleRouteImport } from './routes/_authenticated/role'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReportCategoriesRouteImport } from './routes/_authenticated/report-categories'
import { Route as AuthenticatedProvincesRouteImport } from './routes/_authenticated/provinces'
import { Route as AuthenticatedPlanLeadRequestsRouteImport } from './routes/_authenticated/plan-lead-requests'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedMunicipalitiesRouteImport } from './routes/_authenticated/municipalities'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedModelosRouteImport } from './routes/_authenticated/modelos'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMarcasRouteImport } from './routes/_authenticated/marcas'
import { Route as AuthenticatedFeaturesRouteImport } from './routes/_authenticated/features'
import { Route as AuthenticatedDgtLabelsRouteImport } from './routes/_authenticated/dgt-labels'
import { Route as AuthenticatedDealershipRouteImport } from './routes/_authenticated/dealership'
import { Route as AuthenticatedCuponesRouteImport } from './routes/_authenticated/cupones'
import { Route as AuthenticatedCuotasRouteImport } from './routes/_authenticated/cuotas'
import { Route as AuthenticatedCommunitiesRouteImport } from './routes/_authenticated/communities'
import { Route as AuthenticatedCombustiblesRouteImport } from './routes/_authenticated/combustibles'
import { Route as AuthenticatedColorsRouteImport } from './routes/_authenticated/colors'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCatalogServicesRouteImport } from './routes/_authenticated/catalog-services'
import { Route as AuthenticatedCarroceriasRouteImport } from './routes/_authenticated/carrocerias'
import { Route as AuthenticatedAnosRouteImport } from './routes/_authenticated/anos'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedProfileConfigRouteImport } from './routes/_authenticated/profile/config'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/signIn/',
  path: '/signIn/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoverPasswordRoute = AuthRecoverPasswordRouteImport.update({
  id: '/auth/recover-password',
  path: '/auth/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarrantyTypesRoute =
  AuthenticatedWarrantyTypesRouteImport.update({
    id: '/warranty-types',
    path: '/warranty-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVersionesRoute = AuthenticatedVersionesRouteImport.update({
  id: '/versiones',
  path: '/versiones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehicleTypesRoute =
  AuthenticatedVehicleTypesRouteImport.update({
    id: '/vehicle-types',
    path: '/vehicle-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTractionsRoute = AuthenticatedTractionsRouteImport.update({
  id: '/tractions',
  path: '/tractions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketCategoriesRoute =
  AuthenticatedTicketCategoriesRouteImport.update({
    id: '/ticket-categories',
    path: '/ticket-categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasacionesRoute = AuthenticatedTasacionesRouteImport.update({
  id: '/tasaciones',
  path: '/tasaciones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionPlansRoute =
  AuthenticatedSubscriptionPlansRouteImport.update({
    id: '/subscription-plans',
    path: '/subscription-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoleRoute = AuthenticatedRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportCategoriesRoute =
  AuthenticatedReportCategoriesRouteImport.update({
    id: '/report-categories',
    path: '/report-categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvincesRoute = AuthenticatedProvincesRouteImport.update({
  id: '/provinces',
  path: '/provinces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanLeadRequestsRoute =
  AuthenticatedPlanLeadRequestsRouteImport.update({
    id: '/plan-lead-requests',
    path: '/plan-lead-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMunicipalitiesRoute =
  AuthenticatedMunicipalitiesRouteImport.update({
    id: '/municipalities',
    path: '/municipalities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelosRoute = AuthenticatedModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarcasRoute = AuthenticatedMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeaturesRoute = AuthenticatedFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDgtLabelsRoute = AuthenticatedDgtLabelsRouteImport.update({
  id: '/dgt-labels',
  path: '/dgt-labels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealershipRoute = AuthenticatedDealershipRouteImport.update({
  id: '/dealership',
  path: '/dealership',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuponesRoute = AuthenticatedCuponesRouteImport.update({
  id: '/cupones',
  path: '/cupones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuotasRoute = AuthenticatedCuotasRouteImport.update({
  id: '/cuotas',
  path: '/cuotas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunitiesRoute =
  AuthenticatedCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCombustiblesRoute =
  AuthenticatedCombustiblesRouteImport.update({
    id: '/combustibles',
    path: '/combustibles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColorsRoute = AuthenticatedColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogServicesRoute =
  AuthenticatedCatalogServicesRouteImport.update({
    id: '/catalog-services',
    path: '/catalog-services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarroceriasRoute =
  AuthenticatedCarroceriasRouteImport.update({
    id: '/carrocerias',
    path: '/carrocerias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnosRoute = AuthenticatedAnosRouteImport.update({
  id: '/anos',
  path: '/anos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileConfigRoute =
  AuthenticatedProfileConfigRouteImport.update({
    id: '/profile/config',
    path: '/profile/config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/about': typeof AuthenticatedAboutRoute
  '/anos': typeof AuthenticatedAnosRoute
  '/carrocerias': typeof AuthenticatedCarroceriasRoute
  '/catalog-services': typeof AuthenticatedCatalogServicesRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/colors': typeof AuthenticatedColorsRoute
  '/combustibles': typeof AuthenticatedCombustiblesRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/cuotas': typeof AuthenticatedCuotasRoute
  '/cupones': typeof AuthenticatedCuponesRoute
  '/dealership': typeof AuthenticatedDealershipRoute
  '/dgt-labels': typeof AuthenticatedDgtLabelsRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/marcas': typeof AuthenticatedMarcasRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/municipalities': typeof AuthenticatedMunicipalitiesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/plan-lead-requests': typeof AuthenticatedPlanLeadRequestsRoute
  '/provinces': typeof AuthenticatedProvincesRoute
  '/report-categories': typeof AuthenticatedReportCategoriesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/role': typeof AuthenticatedRoleRoute
  '/subscription-plans': typeof AuthenticatedSubscriptionPlansRoute
  '/tasaciones': typeof AuthenticatedTasacionesRoute
  '/ticket-categories': typeof AuthenticatedTicketCategoriesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/tractions': typeof AuthenticatedTractionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vehicle-types': typeof AuthenticatedVehicleTypesRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/versiones': typeof AuthenticatedVersionesRoute
  '/warranty-types': typeof AuthenticatedWarrantyTypesRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/signIn/': typeof SignInIndexRoute
  '/profile/config': typeof AuthenticatedProfileConfigRoute
}
export interface FileRoutesByTo {
  '/about': typeof AuthenticatedAboutRoute
  '/anos': typeof AuthenticatedAnosRoute
  '/carrocerias': typeof AuthenticatedCarroceriasRoute
  '/catalog-services': typeof AuthenticatedCatalogServicesRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/colors': typeof AuthenticatedColorsRoute
  '/combustibles': typeof AuthenticatedCombustiblesRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/cuotas': typeof AuthenticatedCuotasRoute
  '/cupones': typeof AuthenticatedCuponesRoute
  '/dealership': typeof AuthenticatedDealershipRoute
  '/dgt-labels': typeof AuthenticatedDgtLabelsRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/marcas': typeof AuthenticatedMarcasRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/municipalities': typeof AuthenticatedMunicipalitiesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/plan-lead-requests': typeof AuthenticatedPlanLeadRequestsRoute
  '/provinces': typeof AuthenticatedProvincesRoute
  '/report-categories': typeof AuthenticatedReportCategoriesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/role': typeof AuthenticatedRoleRoute
  '/subscription-plans': typeof AuthenticatedSubscriptionPlansRoute
  '/tasaciones': typeof AuthenticatedTasacionesRoute
  '/ticket-categories': typeof AuthenticatedTicketCategoriesRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/tractions': typeof AuthenticatedTractionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vehicle-types': typeof AuthenticatedVehicleTypesRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/versiones': typeof AuthenticatedVersionesRoute
  '/warranty-types': typeof AuthenticatedWarrantyTypesRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/signIn': typeof SignInIndexRoute
  '/profile/config': typeof AuthenticatedProfileConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/anos': typeof AuthenticatedAnosRoute
  '/_authenticated/carrocerias': typeof AuthenticatedCarroceriasRoute
  '/_authenticated/catalog-services': typeof AuthenticatedCatalogServicesRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/colors': typeof AuthenticatedColorsRoute
  '/_authenticated/combustibles': typeof AuthenticatedCombustiblesRoute
  '/_authenticated/communities': typeof AuthenticatedCommunitiesRoute
  '/_authenticated/cuotas': typeof AuthenticatedCuotasRoute
  '/_authenticated/cupones': typeof AuthenticatedCuponesRoute
  '/_authenticated/dealership': typeof AuthenticatedDealershipRoute
  '/_authenticated/dgt-labels': typeof AuthenticatedDgtLabelsRoute
  '/_authenticated/features': typeof AuthenticatedFeaturesRoute
  '/_authenticated/marcas': typeof AuthenticatedMarcasRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/modelos': typeof AuthenticatedModelosRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/municipalities': typeof AuthenticatedMunicipalitiesRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/plan-lead-requests': typeof AuthenticatedPlanLeadRequestsRoute
  '/_authenticated/provinces': typeof AuthenticatedProvincesRoute
  '/_authenticated/report-categories': typeof AuthenticatedReportCategoriesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/role': typeof AuthenticatedRoleRoute
  '/_authenticated/subscription-plans': typeof AuthenticatedSubscriptionPlansRoute
  '/_authenticated/tasaciones': typeof AuthenticatedTasacionesRoute
  '/_authenticated/ticket-categories': typeof AuthenticatedTicketCategoriesRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/tractions': typeof AuthenticatedTractionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vehicle-types': typeof AuthenticatedVehicleTypesRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/versiones': typeof AuthenticatedVersionesRoute
  '/_authenticated/warranty-types': typeof AuthenticatedWarrantyTypesRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/signIn/': typeof SignInIndexRoute
  '/_authenticated/profile/config': typeof AuthenticatedProfileConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/anos'
    | '/carrocerias'
    | '/catalog-services'
    | '/categories'
    | '/colors'
    | '/combustibles'
    | '/communities'
    | '/cuotas'
    | '/cupones'
    | '/dealership'
    | '/dgt-labels'
    | '/features'
    | '/marcas'
    | '/messages'
    | '/modelos'
    | '/moderation'
    | '/municipalities'
    | '/permissions'
    | '/plan-lead-requests'
    | '/provinces'
    | '/report-categories'
    | '/reports'
    | '/role'
    | '/subscription-plans'
    | '/tasaciones'
    | '/ticket-categories'
    | '/tickets'
    | '/tractions'
    | '/users'
    | '/vehicle-types'
    | '/vehicles'
    | '/versiones'
    | '/warranty-types'
    | '/auth/recover-password'
    | '/auth/reset-password'
    | '/signIn/'
    | '/profile/config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/anos'
    | '/carrocerias'
    | '/catalog-services'
    | '/categories'
    | '/colors'
    | '/combustibles'
    | '/communities'
    | '/cuotas'
    | '/cupones'
    | '/dealership'
    | '/dgt-labels'
    | '/features'
    | '/marcas'
    | '/messages'
    | '/modelos'
    | '/moderation'
    | '/municipalities'
    | '/permissions'
    | '/plan-lead-requests'
    | '/provinces'
    | '/report-categories'
    | '/reports'
    | '/role'
    | '/subscription-plans'
    | '/tasaciones'
    | '/ticket-categories'
    | '/tickets'
    | '/tractions'
    | '/users'
    | '/vehicle-types'
    | '/vehicles'
    | '/versiones'
    | '/warranty-types'
    | '/auth/recover-password'
    | '/auth/reset-password'
    | '/'
    | '/signIn'
    | '/profile/config'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/about'
    | '/_authenticated/anos'
    | '/_authenticated/carrocerias'
    | '/_authenticated/catalog-services'
    | '/_authenticated/categories'
    | '/_authenticated/colors'
    | '/_authenticated/combustibles'
    | '/_authenticated/communities'
    | '/_authenticated/cuotas'
    | '/_authenticated/cupones'
    | '/_authenticated/dealership'
    | '/_authenticated/dgt-labels'
    | '/_authenticated/features'
    | '/_authenticated/marcas'
    | '/_authenticated/messages'
    | '/_authenticated/modelos'
    | '/_authenticated/moderation'
    | '/_authenticated/municipalities'
    | '/_authenticated/permissions'
    | '/_authenticated/plan-lead-requests'
    | '/_authenticated/provinces'
    | '/_authenticated/report-categories'
    | '/_authenticated/reports'
    | '/_authenticated/role'
    | '/_authenticated/subscription-plans'
    | '/_authenticated/tasaciones'
    | '/_authenticated/ticket-categories'
    | '/_authenticated/tickets'
    | '/_authenticated/tractions'
    | '/_authenticated/users'
    | '/_authenticated/vehicle-types'
    | '/_authenticated/vehicles'
    | '/_authenticated/versiones'
    | '/_authenticated/warranty-types'
    | '/auth/recover-password'
    | '/auth/reset-password'
    | '/_authenticated/'
    | '/signIn/'
    | '/_authenticated/profile/config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRecoverPasswordRoute: typeof AuthRecoverPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signIn/': {
      id: '/signIn/'
      path: '/signIn'
      fullPath: '/signIn/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recover-password': {
      id: '/auth/recover-password'
      path: '/auth/recover-password'
      fullPath: '/auth/recover-password'
      preLoaderRoute: typeof AuthRecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warranty-types': {
      id: '/_authenticated/warranty-types'
      path: '/warranty-types'
      fullPath: '/warranty-types'
      preLoaderRoute: typeof AuthenticatedWarrantyTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/versiones': {
      id: '/_authenticated/versiones'
      path: '/versiones'
      fullPath: '/versiones'
      preLoaderRoute: typeof AuthenticatedVersionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicle-types': {
      id: '/_authenticated/vehicle-types'
      path: '/vehicle-types'
      fullPath: '/vehicle-types'
      preLoaderRoute: typeof AuthenticatedVehicleTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tractions': {
      id: '/_authenticated/tractions'
      path: '/tractions'
      fullPath: '/tractions'
      preLoaderRoute: typeof AuthenticatedTractionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ticket-categories': {
      id: '/_authenticated/ticket-categories'
      path: '/ticket-categories'
      fullPath: '/ticket-categories'
      preLoaderRoute: typeof AuthenticatedTicketCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasaciones': {
      id: '/_authenticated/tasaciones'
      path: '/tasaciones'
      fullPath: '/tasaciones'
      preLoaderRoute: typeof AuthenticatedTasacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription-plans': {
      id: '/_authenticated/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/subscription-plans'
      preLoaderRoute: typeof AuthenticatedSubscriptionPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role': {
      id: '/_authenticated/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof AuthenticatedRoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report-categories': {
      id: '/_authenticated/report-categories'
      path: '/report-categories'
      fullPath: '/report-categories'
      preLoaderRoute: typeof AuthenticatedReportCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provinces': {
      id: '/_authenticated/provinces'
      path: '/provinces'
      fullPath: '/provinces'
      preLoaderRoute: typeof AuthenticatedProvincesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan-lead-requests': {
      id: '/_authenticated/plan-lead-requests'
      path: '/plan-lead-requests'
      fullPath: '/plan-lead-requests'
      preLoaderRoute: typeof AuthenticatedPlanLeadRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/municipalities': {
      id: '/_authenticated/municipalities'
      path: '/municipalities'
      fullPath: '/municipalities'
      preLoaderRoute: typeof AuthenticatedMunicipalitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelos': {
      id: '/_authenticated/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthenticatedModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marcas': {
      id: '/_authenticated/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof AuthenticatedMarcasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/features': {
      id: '/_authenticated/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AuthenticatedFeaturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dgt-labels': {
      id: '/_authenticated/dgt-labels'
      path: '/dgt-labels'
      fullPath: '/dgt-labels'
      preLoaderRoute: typeof AuthenticatedDgtLabelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dealership': {
      id: '/_authenticated/dealership'
      path: '/dealership'
      fullPath: '/dealership'
      preLoaderRoute: typeof AuthenticatedDealershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cupones': {
      id: '/_authenticated/cupones'
      path: '/cupones'
      fullPath: '/cupones'
      preLoaderRoute: typeof AuthenticatedCuponesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuotas': {
      id: '/_authenticated/cuotas'
      path: '/cuotas'
      fullPath: '/cuotas'
      preLoaderRoute: typeof AuthenticatedCuotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communities': {
      id: '/_authenticated/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AuthenticatedCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/combustibles': {
      id: '/_authenticated/combustibles'
      path: '/combustibles'
      fullPath: '/combustibles'
      preLoaderRoute: typeof AuthenticatedCombustiblesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colors': {
      id: '/_authenticated/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof AuthenticatedColorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog-services': {
      id: '/_authenticated/catalog-services'
      path: '/catalog-services'
      fullPath: '/catalog-services'
      preLoaderRoute: typeof AuthenticatedCatalogServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carrocerias': {
      id: '/_authenticated/carrocerias'
      path: '/carrocerias'
      fullPath: '/carrocerias'
      preLoaderRoute: typeof AuthenticatedCarroceriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anos': {
      id: '/_authenticated/anos'
      path: '/anos'
      fullPath: '/anos'
      preLoaderRoute: typeof AuthenticatedAnosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/config': {
      id: '/_authenticated/profile/config'
      path: '/profile/config'
      fullPath: '/profile/config'
      preLoaderRoute: typeof AuthenticatedProfileConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAnosRoute: typeof AuthenticatedAnosRoute
  AuthenticatedCarroceriasRoute: typeof AuthenticatedCarroceriasRoute
  AuthenticatedCatalogServicesRoute: typeof AuthenticatedCatalogServicesRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedColorsRoute: typeof AuthenticatedColorsRoute
  AuthenticatedCombustiblesRoute: typeof AuthenticatedCombustiblesRoute
  AuthenticatedCommunitiesRoute: typeof AuthenticatedCommunitiesRoute
  AuthenticatedCuotasRoute: typeof AuthenticatedCuotasRoute
  AuthenticatedCuponesRoute: typeof AuthenticatedCuponesRoute
  AuthenticatedDealershipRoute: typeof AuthenticatedDealershipRoute
  AuthenticatedDgtLabelsRoute: typeof AuthenticatedDgtLabelsRoute
  AuthenticatedFeaturesRoute: typeof AuthenticatedFeaturesRoute
  AuthenticatedMarcasRoute: typeof AuthenticatedMarcasRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedModelosRoute: typeof AuthenticatedModelosRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedMunicipalitiesRoute: typeof AuthenticatedMunicipalitiesRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedPlanLeadRequestsRoute: typeof AuthenticatedPlanLeadRequestsRoute
  AuthenticatedProvincesRoute: typeof AuthenticatedProvincesRoute
  AuthenticatedReportCategoriesRoute: typeof AuthenticatedReportCategoriesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoleRoute: typeof AuthenticatedRoleRoute
  AuthenticatedSubscriptionPlansRoute: typeof AuthenticatedSubscriptionPlansRoute
  AuthenticatedTasacionesRoute: typeof AuthenticatedTasacionesRoute
  AuthenticatedTicketCategoriesRoute: typeof AuthenticatedTicketCategoriesRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedTractionsRoute: typeof AuthenticatedTractionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVehicleTypesRoute: typeof AuthenticatedVehicleTypesRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
  AuthenticatedVersionesRoute: typeof AuthenticatedVersionesRoute
  AuthenticatedWarrantyTypesRoute: typeof AuthenticatedWarrantyTypesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProfileConfigRoute: typeof AuthenticatedProfileConfigRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAnosRoute: AuthenticatedAnosRoute,
  AuthenticatedCarroceriasRoute: AuthenticatedCarroceriasRoute,
  AuthenticatedCatalogServicesRoute: AuthenticatedCatalogServicesRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedColorsRoute: AuthenticatedColorsRoute,
  AuthenticatedCombustiblesRoute: AuthenticatedCombustiblesRoute,
  AuthenticatedCommunitiesRoute: AuthenticatedCommunitiesRoute,
  AuthenticatedCuotasRoute: AuthenticatedCuotasRoute,
  AuthenticatedCuponesRoute: AuthenticatedCuponesRoute,
  AuthenticatedDealershipRoute: AuthenticatedDealershipRoute,
  AuthenticatedDgtLabelsRoute: AuthenticatedDgtLabelsRoute,
  AuthenticatedFeaturesRoute: AuthenticatedFeaturesRoute,
  AuthenticatedMarcasRoute: AuthenticatedMarcasRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedModelosRoute: AuthenticatedModelosRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedMunicipalitiesRoute: AuthenticatedMunicipalitiesRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedPlanLeadRequestsRoute: AuthenticatedPlanLeadRequestsRoute,
  AuthenticatedProvincesRoute: AuthenticatedProvincesRoute,
  AuthenticatedReportCategoriesRoute: AuthenticatedReportCategoriesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoleRoute: AuthenticatedRoleRoute,
  AuthenticatedSubscriptionPlansRoute: AuthenticatedSubscriptionPlansRoute,
  AuthenticatedTasacionesRoute: AuthenticatedTasacionesRoute,
  AuthenticatedTicketCategoriesRoute: AuthenticatedTicketCategoriesRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedTractionsRoute: AuthenticatedTractionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVehicleTypesRoute: AuthenticatedVehicleTypesRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
  AuthenticatedVersionesRoute: AuthenticatedVersionesRoute,
  AuthenticatedWarrantyTypesRoute: AuthenticatedWarrantyTypesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProfileConfigRoute: AuthenticatedProfileConfigRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRecoverPasswordRoute: AuthRecoverPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
